export const demoTranscript = `# Prepare a release summary

> [!NOTE]
> - **Session ID:** \`demo-session-001\`
> - **Started:** 2026-08-26T16:00:00.000Z
> - **Duration:** 2m 18s
> - **Exported:** 2026-08-26T16:02:18.000Z

---

<sub>0s</sub>

## User

Summarize the changes on this branch and prepare a release note.

---

<sub>3s</sub>

## Copilot

I’ll inspect the branch changes and the existing release-note format first.

---

<sub>4s</sub>

## Tool: powershell - Completed

**Arguments**

\`\`\`json
{
  "command": "git diff --stat main...HEAD"
}
\`\`\`

**Result**

\`\`\`text
4 files changed, 182 insertions(+), 31 deletions(-)
\`\`\`

---

<sub>5s</sub>

## Tool: rg - Completed

**Arguments**

\`\`\`json
{
  "pattern": "## Release notes",
  "glob": "*.md"
}
\`\`\`

**Result**

\`\`\`text
CHANGELOG.md:12:## Release notes
\`\`\`

---

<sub>8s</sub>

## Copilot

The branch adds deterministic chat playback, local Markdown import, and configurable animations. I’ll format those changes in the repository’s existing style.

---

<sub>12s</sub>

## Tool: apply_patch - Completed

**Arguments**

\`\`\`text
Updated CHANGELOG.md
\`\`\`

**Result**

\`\`\`text
Added release notes for the chat replay experience.
\`\`\`

---

<sub>14s</sub>

## Copilot

Release notes are ready. They highlight the local-only transcript import, click-through playback, and compact tool-call summaries.

---

Generated by [GitHub Copilot](https://github.com/features/copilot)`;
