export const demoTranscript = `# Prepare a release summary

> [!NOTE]
> - **Session ID:** \`demo-session-001\`
> - **Started:** 2026-08-26T16:00:00.000Z
> - **Duration:** 2m 18s
> - **Exported:** 2026-08-26T16:02:18.000Z

---

<sub>0s</sub>

## User

Summarize the changes on this branch and prepare a release note.

---

<sub>1s</sub>

## Tool: skill - Completed

**Arguments**

\`\`\`json
{
  "skill": "release-note-writer"
}
\`\`\`

**Result**

\`\`\`text
Skill "release-note-writer" loaded successfully.
\`\`\`

---

<sub>3s</sub>

## Copilot

I’ll inspect the branch changes and the existing release-note format first.

---

<sub>4s</sub>

## Tool: powershell - Completed

**Arguments**

\`\`\`json
{
  "command": "git diff --stat main...HEAD"
}
\`\`\`

**Result**

\`\`\`text
4 files changed, 182 insertions(+), 31 deletions(-)
\`\`\`

---

<sub>5s</sub>

## Tool: rg - Completed

**Arguments**

\`\`\`json
{
  "pattern": "## Release notes",
  "glob": "*.md"
}
\`\`\`

**Result**

\`\`\`text
CHANGELOG.md:12:## Release notes
\`\`\`

---

<sub>8s</sub>

## Copilot

The branch adds deterministic chat playback, local Markdown import, and configurable animations. I’ll format those changes in the repository’s existing style.

---

<sub>9s</sub>

## Tool: ask_user - Completed

**Arguments**

\`\`\`json
{
  "question": "Which format should I use for the release note?",
  "choices": [
    "Match the existing changelog style (Recommended)",
    "Use a concise standalone summary"
  ]
}
\`\`\`

**Result**

\`\`\`text
User selected: Match the existing changelog style (Recommended)
\`\`\`

---

<sub>12s</sub>

## Tool: apply_patch - Completed

**Arguments**

\`\`\`text
Updated CHANGELOG.md
\`\`\`

**Result**

\`\`\`text
Added release notes for the chat replay experience.
\`\`\`

---

<sub>13s</sub>

## Tool: ask_user - Completed

**Arguments**

\`\`\`json
{
  "question": "Who is the primary audience for this release note?",
  "choices": [
    "Application developers",
    "End users"
  ]
}
\`\`\`

**Result**

\`\`\`text
User answered: Internal platform maintainers
\`\`\`

---

<sub>14s</sub>

## Copilot

Release notes are ready for internal platform maintainers. They match the existing changelog style and highlight local-only transcript import, click-through playback, and compact tool-call summaries.

---

Generated by [GitHub Copilot](https://github.com/features/copilot)`;
