import type {
  PlaybackStep,
  SessionEvent,
  ToolEvent,
  ToolPayload,
  Transcript,
  TranscriptMetadata,
} from "./types";

const EVENT_HEADING = /^##\s+(User|Copilot|Tool:\s+.+)$/;
const ELAPSED_LINE = /^<sub>(.*?)<\/sub>$/;

export class TranscriptParseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TranscriptParseError";
  }
}

function isFenceClose(line: string, marker: string): boolean {
  const trimmed = line.trim();
  return (
    trimmed.length >= marker.length &&
    trimmed[0] === marker[0] &&
    trimmed.split(marker[0]).length - 1 >= marker.length &&
    new RegExp(`^\\${marker[0]}{${marker.length},}\\s*$`).test(trimmed)
  );
}

function findEventStarts(lines: string[]): number[] {
  const starts: number[] = [];
  let fence = "";

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    const fenceMatch = line.match(/^\s*(`{3,}|~{3,})/);

    if (fence) {
      if (isFenceClose(line, fence)) {
        fence = "";
      }
      continue;
    }

    if (fenceMatch) {
      fence = fenceMatch[1];
      continue;
    }

    if (line.trim() !== "---") {
      continue;
    }

    let elapsedIndex = index + 1;
    while (elapsedIndex < lines.length && !lines[elapsedIndex].trim()) {
      elapsedIndex += 1;
    }

    let headingIndex = elapsedIndex + 1;
    while (headingIndex < lines.length && !lines[headingIndex].trim()) {
      headingIndex += 1;
    }

    if (
      ELAPSED_LINE.test(lines[elapsedIndex]?.trim() ?? "") &&
      EVENT_HEADING.test(lines[headingIndex]?.trim() ?? "")
    ) {
      starts.push(elapsedIndex);
    }
  }

  return starts;
}

function getEventBlocks(markdown: string): string[] {
  const lines = markdown.replace(/\r\n?/g, "\n").split("\n");
  const starts = findEventStarts(lines);

  return starts.map((start, blockIndex) => {
    const end = starts[blockIndex + 1] ?? lines.length;
    const blockLines = lines.slice(start, end);

    while (!blockLines.at(-1)?.trim()) {
      blockLines.pop();
    }
    if (blockLines.at(-1)?.trim() === "---") {
      blockLines.pop();
    }

    return blockLines
      .join("\n")
      .replace(
        /\n---\s*\n\s*Generated by \[GitHub Copilot\]\(https:\/\/github\.com\/features\/copilot\)\s*$/i,
        "",
      )
      .trim();
  });
}

function parseMetadata(markdown: string): TranscriptMetadata {
  const readValue = (label: string): string | undefined => {
    const escapedLabel = label.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const match = markdown.match(
      new RegExp(
        `^>\\s*-\\s*\\*\\*${escapedLabel}:\\*\\*\\s*(?:\`([^\`\\n]+)\`|([^\\n]+))`,
        "im",
      ),
    );
    return (match?.[1] ?? match?.[2])?.trim();
  };

  return {
    sessionId: readValue("Session ID"),
    started: readValue("Started"),
    duration: readValue("Duration"),
    exported: readValue("Exported"),
  };
}

export function parseElapsedSeconds(value: string): number {
  const unitPattern = /(\d+(?:\.\d+)?)\s*(d|h|m|s)\b/gi;
  const unitSeconds = { d: 86_400, h: 3_600, m: 60, s: 1 };
  let total = 0;
  let match: RegExpExecArray | null;

  while ((match = unitPattern.exec(value)) !== null) {
    total += Number(match[1]) * unitSeconds[match[2].toLowerCase() as keyof typeof unitSeconds];
  }

  return total;
}

function readPayload(section: string): ToolPayload | undefined {
  const trimmed = section.trim();
  if (!trimmed) {
    return undefined;
  }

  const fenced = trimmed.match(/^(`{3,}|~{3,})([^\n]*)\n([\s\S]*?)\n\1\s*$/);
  if (!fenced) {
    return { language: "", content: trimmed };
  }

  return {
    language: fenced[2].trim(),
    content: fenced[3],
  };
}

function parseToolContent(content: string): Pick<ToolEvent, "arguments" | "result"> {
  const argumentsMatch = /^\*\*Arguments\*\*\s*$/im.exec(content);
  const resultMatch = /^\*\*Result\*\*\s*$/im.exec(content);

  if (!argumentsMatch && !resultMatch) {
    return { result: readPayload(content) };
  }

  const argumentsStart = argumentsMatch
    ? argumentsMatch.index + argumentsMatch[0].length
    : undefined;
  const resultStart = resultMatch ? resultMatch.index + resultMatch[0].length : undefined;

  return {
    arguments:
      argumentsStart === undefined
        ? undefined
        : readPayload(content.slice(argumentsStart, resultMatch?.index ?? content.length)),
    result: resultStart === undefined ? undefined : readPayload(content.slice(resultStart)),
  };
}

function parseEventBlock(block: string, index: number): SessionEvent | undefined {
  const lines = block.split("\n");
  let cursor = 0;

  while (cursor < lines.length && !lines[cursor].trim()) {
    cursor += 1;
  }

  const elapsedMatch = lines[cursor]?.trim().match(ELAPSED_LINE);
  if (!elapsedMatch) {
    return undefined;
  }

  cursor += 1;
  while (cursor < lines.length && !lines[cursor].trim()) {
    cursor += 1;
  }

  const heading = lines[cursor]?.trim() ?? "";
  if (!EVENT_HEADING.test(heading)) {
    return undefined;
  }

  cursor += 1;
  while (cursor < lines.length && !lines[cursor].trim()) {
    cursor += 1;
  }

  const rawContent = lines.slice(cursor).join("\n").trim();
  const base = {
    id: `event-${index + 1}`,
    index,
    elapsedLabel: elapsedMatch[1].trim(),
    elapsedSeconds: parseElapsedSeconds(elapsedMatch[1]),
    rawContent,
  };

  if (heading === "## User" || heading === "## Copilot") {
    return {
      ...base,
      kind: "message",
      role: heading === "## User" ? "user" : "copilot",
    };
  }

  const toolMatch = heading.match(/^## Tool:\s+(.+?)\s+-\s+(.+)$/);
  if (!toolMatch) {
    return undefined;
  }

  return {
    ...base,
    kind: "tool",
    name: toolMatch[1].trim(),
    status: toolMatch[2].trim(),
    ...parseToolContent(rawContent),
  };
}

export function parseTranscript(markdown: string, sourceName = "Pasted session"): Transcript {
  const normalized = markdown.replace(/^\uFEFF/, "").trim();
  if (!normalized) {
    throw new TranscriptParseError("Add an exported Copilot session before starting the replay.");
  }

  const title = normalized.match(/^#\s+(.+)$/m)?.[1].trim() ?? "Untitled Copilot session";
  const events = getEventBlocks(normalized)
    .map(parseEventBlock)
    .filter((event): event is SessionEvent => Boolean(event));

  if (!events.length) {
    throw new TranscriptParseError(
      "No Copilot chat turns were found. Use a session export with <sub> timestamps and User, Copilot, or Tool headings.",
    );
  }

  return {
    title,
    metadata: parseMetadata(normalized),
    events,
    sourceName,
  };
}

export function createPlaybackSteps(
  events: SessionEvent[],
  collapseTools: boolean,
): PlaybackStep[] {
  const steps: PlaybackStep[] = [];

  for (let index = 0; index < events.length; index += 1) {
    const event = events[index];

    if (event.kind === "message") {
      steps.push({ id: event.id, kind: "message", event });
      continue;
    }

    const tools = [event];
    if (collapseTools) {
      while (events[index + 1]?.kind === "tool") {
        index += 1;
        tools.push(events[index] as ToolEvent);
      }
    }

    steps.push({
      id: `tools-${tools[0].id}-${tools.at(-1)?.id}`,
      kind: "tools",
      events: tools,
    });
  }

  return steps;
}
